######################################################################
# Automatically generated by qmake (3.0) Tue Aug 26 16:16:12 2014
######################################################################

QT = core gui widgets

TEMPLATE = app
TARGET = qt1
INCLUDEPATH += .

# Input
SOURCES += qt1.cpp
