client32:
	gcc -o bin/client32 src/client32.c

server32:
	gcc -o bin/server32 src/server32.c

client33:
	gcc -o bin/client33 src/client33.c

server33:
	gcc -o bin/server33 src/server33.c

clean:
	rm bin/*
