
add_num_MPI:
	mpic++ src/add_num_MPI.cpp -o bin/add_num_MPI

add_num_MPI_rev1:
	mpic++ src/add_num_MPI_rev1.cpp -o bin/add_num_MPI_rev1

add_num_MPI_rev2:
	mpic++ src/add_num_MPI_rev2.cpp -o bin/add_num_MPI_rev2

add_num_MPI_rev3:
	mpic++ src/add_num_MPI_rev3.cpp -o bin/add_num_MPI_rev3

clean:
	rm bin/*
