/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
 *
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 416
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

const int IIRL_22050 = 4;
const float IIR_22050[4] = {
  0.0006744638599687,0.0002687078121714,0.0002849351700702,0.0002703450167427
};

const int IIRL_44100 = 4;
const float IIR_44100[4] = {
  0.0006744638599687,0.0002687078121714,0.0002849351700702,0.0002703450167427
};
