/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
 *
 * Generated on: 15-Apr-2015 03:02:45
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 12
 * Denominator Length  : 12
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2012a_Student/extern/include/tmwtypes.h 
 */
const int NL = 12;
const real64_T NUM[12] = {
  2.731758313976e-10,3.004934145373e-09,1.502467072687e-08, 4.50740121806e-08,
   9.01480243612e-08,1.262072341057e-07,1.262072341057e-07, 9.01480243612e-08,
   4.50740121806e-08,1.502467072687e-08,3.004934145373e-09,2.731758313976e-10
};
const int DL = 12;
const real64_T DEN[12] = {
                   1,   -9.932155633877,    45.42862235097,   -126.2638893873,
      236.8802991527,   -314.9017369565,    302.6376457588,   -210.2455345471,
      103.4637393698,   -34.34900807516,    6.924121412451,  -0.6421028852943
};
