/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
 *
 * Generated on: 15-Apr-2015 02:53:54
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2012a_Student/extern/include/tmwtypes.h 
 */
const int NL = 11;
const real64_T NUM[11] = {
   1.75527846804e-12, 1.75527846804e-11,7.898753106178e-11,2.106334161647e-10,
  3.686084782883e-10, 4.42330173946e-10,3.686084782883e-10,2.106334161647e-10,
  7.898753106178e-11, 1.75527846804e-11, 1.75527846804e-12
};
const int DL = 11;
const real64_T DEN[11] = {
                   1,    -9.64869768027,    42.02918268338,    -108.837094215,
      185.5445450459,   -217.5849281568,     177.748137936,   -99.87947573383,
      36.94568719833,   -8.123651191181,   0.8062941155919
};
