/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
 *
 * Generated on: 14-Apr-2015 11:44:48
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 32
 * Denominator Length  : 32
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/*
 * Expected path to tmwtypes.h
 * /usr/local/MATLAB/R2012a_Student/extern/include/tmwtypes.h
 */
const int NL_22050 = 12;
const real64_T NUM_22050[12] = {
  2.731758313976e-10,3.004934145373e-09,1.502467072687e-08, 4.50740121806e-08,
   9.01480243612e-08,1.262072341057e-07,1.262072341057e-07, 9.01480243612e-08,
   4.50740121806e-08,1.502467072687e-08,3.004934145373e-09,2.731758313976e-10
};

const int DL_22050 = 12;
const real64_T DEN_22050[12] = {
                   1,   -9.932155633877,    45.42862235097,   -126.2638893873,
      236.8802991527,   -314.9017369565,    302.6376457588,   -210.2455345471,
      103.4637393698,   -34.34900807516,    6.924121412451,  -0.6421028852943
};

const int NL_44100 = 11;
const real64_T NUM_44100[11] = {
   1.75527846804e-12, 1.75527846804e-11,7.898753106178e-11,2.106334161647e-10,
  3.686084782883e-10, 4.42330173946e-10,3.686084782883e-10,2.106334161647e-10,
  7.898753106178e-11, 1.75527846804e-11, 1.75527846804e-12
};

const int DL_44100 = 11;
const real64_T DEN_44100[11] = {
                   1,    -9.64869768027,    42.02918268338,    -108.837094215,
      185.5445450459,   -217.5849281568,     177.748137936,   -99.87947573383,
      36.94568719833,   -8.123651191181,   0.8062941155919
};

